env = "Development"

[server]
url = "127.0.0.1"
fqdn = "http://127.0.0.1:3000"
api_fqdn = "http://127.0.0.1:8000/api"
jwt_secret = "super-secret-key"

[database]
url = "postgresql://chameleon:chameleon@127.0.0.1:5432/chameleon"
max_connections = 5

[cdn]
file_store = "Local"

[log]
level = "Debug"
